sudo: required
services:
  - docker
before_install:
  - docker build -t merajhussain/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run merajhussain/react-test npm test -- --coverage
after_sucess:
  - docker build -t merajhussain1/multi-client ./client
  - docker build -t merajhussain1/multi-nginx ./nginx
  - docker build -t merajhussain1/multi-server ./server
  - docker build -t merajhussain1/multi-worker ./worker

  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -password-stdin
  #take those images and push them to docker hub
  - docker push merajhussain1/multi-client
  - docker push merajhussain1/multi-nginx
  - docker push merajhussain1/multi-server
  - docker push merajhussain1/multi-worker

  ## logged in from ot 


